package com.glv.gsysportal.service;

import com.glv.gsysportal.domain.OfficialPoShortCode;
import com.glv.gsysportal.exception.OfficialPoShortCodeNotConfiguredException;
import com.glv.gsysportal.repository.prototype.OfficialPoShortCodeRepository;
import org.springframework.stereotype.Component;

/**
 * BR-07/BR-08 (docs/gulliver-20260917-confirmed-business-rules.md): the
 * Official PO No. is auto-numbered by G-OPS, never staff-entered -
 * {@code {SupplierShortCode}{BrandShortCode}{3-digit sequence}}, e.g.
 * {@code ABCXYZ001}. The sequence is counted per Supplier x Brand
 * combination ({@link OfficialPoSequenceService}); the two 3-character
 * abbreviations are never generated by G-OPS itself - only read from
 * whatever an ADMIN has registered in {@link OfficialPoShortCodeRepository}
 * on Gulliver's behalf (BR-08's explicit "G-OPSが略称を勝手に生成・変更しない").
 */
@Component
public class OfficialPoNumberGenerator {

    private final OfficialPoShortCodeRepository shortCodeRepository;
    private final OfficialPoSequenceService sequenceService;

    public OfficialPoNumberGenerator(OfficialPoShortCodeRepository shortCodeRepository,
                                      OfficialPoSequenceService sequenceService) {
        this.shortCodeRepository = shortCodeRepository;
        this.sequenceService = sequenceService;
    }

    public String generate(String supplierCode, String brandCode) {
        String supplierShortCode = resolveShortCode(OfficialPoShortCode.TYPE_SUPPLIER, supplierCode);
        String brandShortCode = resolveShortCode(OfficialPoShortCode.TYPE_BRAND, brandCode);
        int seq = sequenceService.nextSequence(supplierCode, brandCode);
        return supplierShortCode + brandShortCode + String.format("%03d", seq);
    }

    private String resolveShortCode(String codeType, String businessCode) {
        return shortCodeRepository.findFirstByCodeTypeAndBusinessCodeAndActiveTrue(codeType, businessCode)
                .map(OfficialPoShortCode::getShortCode)
                .orElseThrow(() -> new OfficialPoShortCodeNotConfiguredException(codeType, businessCode));
    }
}
