package com.glv.gsysportal.service;

import com.glv.gsysportal.domain.OfficialPoShortCode;
import com.glv.gsysportal.exception.OfficialPoShortCodeNotConfiguredException;
import com.glv.gsysportal.repository.prototype.OfficialPoShortCodeRepository;
import org.springframework.stereotype.Component;

/**
 * BR-07/BR-08 (docs/gulliver-20260917-confirmed-business-rules.md) as
 * reconciled by the Legacy-compatibility findings in
 * docs/ux-audit/gops-official-po-number-final-reality-audit.md: the
 * Official PO No. is auto-numbered by G-OPS, never staff-entered -
 * {@code #{SupplierShortCode}-{BrandShortCode}{3-digit sequence}}, e.g.
 * {@code #ABC-DEF001}. This is the format Legacy's own {@code
 * BusinessLogicUtil} parser and real Supplier/Brand masters already use in
 * 99.98% of 8,376 real historical POs (100% of the last 12/6/3 months) -
 * the prior, no-separator {@code ABCXYZ001} shape this class used to
 * produce was mechanically rejected by {@code PrOfficialPoImportBatch} at
 * its very first validation gate (fewer than its required 11 characters),
 * with zero historical precedent, per that same audit's §12/§5-§6. The
 * sequence is counted per Supplier x Brand combination
 * ({@link OfficialPoSequenceService}, unchanged this Phase); the two
 * 3-character abbreviations are never generated by G-OPS itself - only
 * read from whatever an ADMIN has registered in
 * {@link OfficialPoShortCodeRepository} on Gulliver's behalf (BR-08's
 * explicit "G-OPSが略称を勝手に生成・変更しない"). The Supplier Short Code
 * (3 chars, e.g. {@code ABC}) is registered WITHOUT the leading {@code #}
 * that Legacy's own real Supplier Master code carries (e.g. {@code #ABC})
 * - this class adds the {@code #} back at generation time; the two are
 * never to be confused (an ADMIN must never be asked to type the {@code #}
 * itself into the Short Code field).
 */
@Component
public class OfficialPoNumberGenerator {

    private final OfficialPoShortCodeRepository shortCodeRepository;
    private final OfficialPoSequenceService sequenceService;

    public OfficialPoNumberGenerator(OfficialPoShortCodeRepository shortCodeRepository,
                                      OfficialPoSequenceService sequenceService) {
        this.shortCodeRepository = shortCodeRepository;
        this.sequenceService = sequenceService;
    }

    public String generate(String supplierCode, String brandCode) {
        String supplierShortCode = resolveShortCode(OfficialPoShortCode.TYPE_SUPPLIER, supplierCode);
        String brandShortCode = resolveShortCode(OfficialPoShortCode.TYPE_BRAND, brandCode);
        int seq = sequenceService.nextSequence(supplierCode, brandCode);
        return "#" + supplierShortCode + "-" + brandShortCode + String.format("%03d", seq);
    }

    private String resolveShortCode(String codeType, String businessCode) {
        return shortCodeRepository.findFirstByCodeTypeAndBusinessCodeAndActiveTrue(codeType, businessCode)
                .map(OfficialPoShortCode::getShortCode)
                .orElseThrow(() -> new OfficialPoShortCodeNotConfiguredException(codeType, businessCode));
    }
}
