-- Gap Analysis Phase 4-8 (docs/gulliver-20260917-phase1-gap-analysis.md):
-- extends ck_audit_event_type with the new event types this Phase's
-- features write (PDF generation, Official PO Reissue/Cancel, Email
-- Recipient Override). Same drop-and-recreate-the-whole-allowlist pattern
-- every prior feature migration touching this constraint has used (see
-- V22__order_email_send.sql for the immediately preceding version) - not a
-- new pattern.
ALTER TABLE audit_event DROP CONSTRAINT ck_audit_event_type;
ALTER TABLE audit_event ADD CONSTRAINT ck_audit_event_type CHECK (event_type IN (
    'ORDER_DRAFT_CREATED','ORDER_QTY_CHANGED','ORDER_READY','DEMO_SENT','STATUS_CHANGED',
    'SUPPLIER_RESPONSE_RECEIVED','QUANTITY_CHANGED','DELIVERY_CHANGED',
    'ATTENTION_ADDED','ATTENTION_RESOLVED','REQUESTED_DELIVERY_CHANGED','REMARK_CHANGED',
    'ORDER_DATE_CHANGED','ORDER_RETURNED_TO_DRAFT',
    'SUBMITTED_FOR_APPROVAL','ORDER_APPROVED','APPROVED_WITH_CHANGES','RETURNED_FOR_CORRECTION',
    'OFFICIAL_PO_INTEGRATION_REQUESTED','PRECHECK_COMPLETED',
    'MAIL_PREVIEW_GENERATED',
    'SUPPLIER_RESPONSE_AGREED','ORDER_REVISION_CREATED','AGREEMENT_REOPENED',
    'FOLLOW_UP_CREATED','FOLLOW_UP_UPDATED','FOLLOW_UP_CLOSED','REORDER_CREATED',
    'LEGACY_PO_BASELINE_CAPTURED','LEGACY_PO_CHANGE_DETECTED',
    'EDI_SEND_RECORDED',
    'PRICE_CHANGE_SET_CREATED','PRICE_CHANGE_DETAIL_ADDED','PRICE_CHANGE_PROPOSED_PRICE_CHANGED',
    'PRICE_CHANGE_DETAIL_REMOVED','PRICE_CHANGE_NOTE_CHANGED',
    'OFFICIAL_PO_NUMBER_CONFIRMED','OFFICIAL_PO_EXCEL_GENERATED',
    'OFFICIAL_PO_FILE_PLACED','OFFICIAL_PO_FILE_PLACEMENT_FAILED',
    'OFFICIAL_PO_IMPORT_CONFIRMED',
    'EDI_INPUT_COMPLETED',
    'EMAIL_SENT','EMAIL_SEND_FAILED',
    'OFFICIAL_PO_PDF_GENERATED','OFFICIAL_PO_REISSUED','OFFICIAL_PO_CANCELLED',
    'EMAIL_RECIPIENT_OVERRIDE_USED'
));
